/****** Object:  Table [dbo].[CacheSettings]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CacheSettings](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_CDNSERVER] [int] NOT NULL,
	[TYPE] [nvarchar](20) NOT NULL,
	[PAYLOAD] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CacheSettings] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cartelle]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cartelle](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[PARENT_FOLDER] [int] NULL,
	[NOTE] [nvarchar](max) NULL,
	[ELIMINABILE] [bit] NOT NULL,
 CONSTRAINT [PK_Cartelle] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CdnServers]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CdnServers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](200) NOT NULL,
	[BASEURL] [nvarchar](500) NOT NULL,
	[TIPO] [int] NOT NULL,
 CONSTRAINT [PK_CdnServers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CdnServersPerVendor]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CdnServersPerVendor](
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[FK_CDNSERVER] [int] NOT NULL,
 CONSTRAINT [PK_CdnServersPerVendor] PRIMARY KEY CLUSTERED 
(
	[FK_VENDOR] ASC,
	[FK_CDNSERVER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contenuti]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contenuti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITOLO] [nvarchar](250) NOT NULL,
	[CONTENUTO] [ntext] NULL,
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[FK_ISTANZA] [nvarchar](20) NULL,
	[FK_TIPOLOGIA] [int] NOT NULL,
	[FK_LINGUA] [nchar](2) NOT NULL,
	[GENERA_PDF] [bit] NOT NULL,
	[ATTIVA] [bit] NOT NULL,
	[UTENTE_CREAZIONE] [nvarchar](50) NOT NULL,
	[UTENTE_ULTIMA_MODIFICA] [nvarchar](50) NOT NULL,
	[DATA_CREAZIONE] [datetime] NOT NULL,
	[DATA_ULTIMO_AGGIORNAMENTO] [datetime] NOT NULL,
 CONSTRAINT [PK_Contenuti] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Files]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Files](
	[ID] [uniqueidentifier] NOT NULL,
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[FILENAME] [nvarchar](255) NOT NULL,
	[CONTENT] [varbinary](max) NOT NULL,
	[THUMBNAIL] [varbinary](max) NULL,
	[FK_FOLDER] [int] NOT NULL,
	[DATA_CREAZIONE] [datetime] NOT NULL,
	[UTENTE_CREAZIONE] [nvarchar](50) NOT NULL,
	[DATA_ULTIMA_MODIFICA] [datetime] NOT NULL,
	[UTENTE_ULTIMA_MODIFICA] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FtpServers]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FtpServers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](250) NOT NULL,
	[HOST] [nvarchar](250) NOT NULL,
	[PORT] [int] NULL,
	[USERNAME] [nvarchar](250) NULL,
	[PASSWORD] [nvarchar](250) NULL,
	[TIPO] [int] NOT NULL,
 CONSTRAINT [PK_FtpServers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FtpServersPerCdnServer]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FtpServersPerCdnServer](
	[FK_FTPSERVER] [int] NOT NULL,
	[FK_CDNSERVER] [int] NOT NULL,
 CONSTRAINT [PK_FtpServersPerCdnServer] PRIMARY KEY CLUSTERED 
(
	[FK_FTPSERVER] ASC,
	[FK_CDNSERVER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Generazioni]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Generazioni](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[PAYLOAD] [nvarchar](max) NOT NULL,
	[FK_CDNSERVER] [int] NULL,
	[FK_FTPSERVER] [int] NULL,
	[TIPO_ESPORTAZIONE] [int] NOT NULL,
	[FK_UTENTE] [nvarchar](50) NOT NULL,
	[DATA_FILTROGENERAZIONE_FILE] [datetime] NOT NULL,
	[ZIP_FILE] [varbinary](max) NULL,
	[ULTIMO_AGGIORNAMENTO] [datetime] NOT NULL,
	[PRESERVACOPIA] [bit] NOT NULL,
	[STATUS_CODE] [int] NOT NULL,
	[WEBSITE] [nvarchar](500) NULL,
	[STATUS] [nvarchar](250) NOT NULL,
	[EMAIL] [nvarchar](100) NULL,
	[TYPE] [int] NULL,
 CONSTRAINT [PK_Generazioni_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Risorse]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Risorse](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](250) NOT NULL,
	[FK_ISTANZA] [nvarchar](20) NULL,
	[FK_LINGUA] [nchar](2) NOT NULL,
	[FK_TIPOLOGIA] [int] NULL,
	[FK_NAZIONE] [char](2) NULL,
	[ATTIVA] [bit] NOT NULL,
	[FK_VENDOR] [nvarchar](20) NULL,
 CONSTRAINT [PK_Resources] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TestiPerRisorsa]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestiPerRisorsa](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RISORSA] [int] NOT NULL,
	[TESTO] [nvarchar](max) NULL,
	[REVISIONE] [int] NOT NULL,
	[DATA_CREAZIONE] [datetime] NOT NULL,
	[UTENTE_CREAZIONE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Testo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipologieContenuti]    Script Date: 7/9/2022 11:31:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipologieContenuti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](250) NOT NULL,
	[OUTPUT_FILENAME] [nvarchar](250) NOT NULL,
	[XMLSCHEMA] [xml] NOT NULL,
	[FK_VENDOR] [nvarchar](20) NULL,
	[SUBFOLDER] [nvarchar](250) NULL,
	[PATH_PAGINAPREVIEW] [nvarchar](max) NULL,
	[PRINT_ELEMENT_NAME] [nvarchar](250) NULL,
	[VISIBILITA] [nvarchar](500) NULL,
 CONSTRAINT [PK_TipologieContenuti] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipologieTesti]    Script Date: 7/9/2022 11:31:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipologieTesti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPOLOGIA] [nvarchar](250) NOT NULL,
	[NOTE] [ntext] NULL,
	[SUBFOLDER] [nvarchar](250) NULL,
 CONSTRAINT [PK_TipologieTesti] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIpologieTestiPerVendor]    Script Date: 7/9/2022 11:31:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIpologieTestiPerVendor](
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[FK_RESOURCETYPE] [int] NOT NULL,
 CONSTRAINT [PK_TIpologieTestiPerVendor] PRIMARY KEY CLUSTERED 
(
	[FK_VENDOR] ASC,
	[FK_RESOURCETYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WebsitesPerVendor]    Script Date: 7/9/2022 11:31:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WebsitesPerVendor](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_VENDOR] [nvarchar](20) NOT NULL,
	[TIPO] [int] NOT NULL,
	[URL] [nvarchar](500) NOT NULL,
	[NOTE] [nvarchar](500) NULL,
 CONSTRAINT [PK_WebsitesPerVendor] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WidgetContenuti]    Script Date: 7/9/2022 11:31:01 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WidgetContenuti](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CHIAVE] [nvarchar](250) NOT NULL,
	[FK_VENDOR] [nvarchar](20) NULL,
	[FK_ISTANZA] [nvarchar](20) NULL,
	[FK_LINGUA] [nchar](2) NOT NULL,
	[CONTENUTO] [nvarchar](max) NULL,
	[UTENTE_CREAZIONE] [nvarchar](50) NOT NULL,
	[UTENTE_ULTIMA_MODIFICA] [nvarchar](50) NOT NULL,
	[DATA_CREAZIONE] [datetime] NOT NULL,
	[DATA_ULTIMA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_WidgetContenuti] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cartelle] ADD  CONSTRAINT [DF_Cartelle_ELIMINABILE]  DEFAULT ((1)) FOR [ELIMINABILE]
GO
ALTER TABLE [dbo].[Contenuti] ADD  CONSTRAINT [DF_Contenuti_GENERA_PDF]  DEFAULT ((0)) FOR [GENERA_PDF]
GO
ALTER TABLE [dbo].[Contenuti] ADD  CONSTRAINT [DF_Contenuti_ATTIVA]  DEFAULT ((1)) FOR [ATTIVA]
GO
ALTER TABLE [dbo].[FtpServers] ADD  CONSTRAINT [DF__FtpServer__ONLIN__44FF419A]  DEFAULT ((0)) FOR [TIPO]
GO
ALTER TABLE [dbo].[Generazioni] ADD  CONSTRAINT [DF_Generazioni_DATA_FILTROGENERAZIONE_FILE]  DEFAULT (getdate()) FOR [DATA_FILTROGENERAZIONE_FILE]
GO
ALTER TABLE [dbo].[Generazioni] ADD  CONSTRAINT [DF__Generazio__STATU__4AB81AF0]  DEFAULT ((0)) FOR [STATUS_CODE]
GO
ALTER TABLE [dbo].[Risorse] ADD  CONSTRAINT [DF_Risorse_ATTIVA]  DEFAULT ((1)) FOR [ATTIVA]
GO
ALTER TABLE [dbo].[CacheSettings]  WITH CHECK ADD  CONSTRAINT [FK_CacheSettings_CdnServers] FOREIGN KEY([FK_CDNSERVER])
REFERENCES [dbo].[CdnServers] ([ID])
GO
ALTER TABLE [dbo].[CacheSettings] CHECK CONSTRAINT [FK_CacheSettings_CdnServers]
GO
ALTER TABLE [dbo].[Cartelle]  WITH CHECK ADD  CONSTRAINT [FK_Cartelle_Cartelle] FOREIGN KEY([PARENT_FOLDER])
REFERENCES [dbo].[Cartelle] ([ID])
GO
ALTER TABLE [dbo].[Cartelle] CHECK CONSTRAINT [FK_Cartelle_Cartelle]
GO
ALTER TABLE [dbo].[CdnServersPerVendor]  WITH CHECK ADD  CONSTRAINT [FK_CdnServersPerVendor_CdnServers] FOREIGN KEY([FK_CDNSERVER])
REFERENCES [dbo].[CdnServers] ([ID])
GO
ALTER TABLE [dbo].[CdnServersPerVendor] CHECK CONSTRAINT [FK_CdnServersPerVendor_CdnServers]
GO
ALTER TABLE [dbo].[Contenuti]  WITH CHECK ADD  CONSTRAINT [FK_Contenuti_TipologieContenuti] FOREIGN KEY([FK_TIPOLOGIA])
REFERENCES [dbo].[TipologieContenuti] ([ID])
GO
ALTER TABLE [dbo].[Contenuti] CHECK CONSTRAINT [FK_Contenuti_TipologieContenuti]
GO
ALTER TABLE [dbo].[Files]  WITH CHECK ADD  CONSTRAINT [FK_Files_Files] FOREIGN KEY([FK_FOLDER])
REFERENCES [dbo].[Cartelle] ([ID])
GO
ALTER TABLE [dbo].[Files] CHECK CONSTRAINT [FK_Files_Files]
GO
ALTER TABLE [dbo].[FtpServersPerCdnServer]  WITH CHECK ADD  CONSTRAINT [FK_FtpServersPerCdnServer_CdnServers] FOREIGN KEY([FK_CDNSERVER])
REFERENCES [dbo].[CdnServers] ([ID])
GO
ALTER TABLE [dbo].[FtpServersPerCdnServer] CHECK CONSTRAINT [FK_FtpServersPerCdnServer_CdnServers]
GO
ALTER TABLE [dbo].[FtpServersPerCdnServer]  WITH CHECK ADD  CONSTRAINT [FK_FtpServersPerCdnServer_FtpServers] FOREIGN KEY([FK_FTPSERVER])
REFERENCES [dbo].[FtpServers] ([Id])
GO
ALTER TABLE [dbo].[FtpServersPerCdnServer] CHECK CONSTRAINT [FK_FtpServersPerCdnServer_FtpServers]
GO
ALTER TABLE [dbo].[Generazioni]  WITH CHECK ADD  CONSTRAINT [FK_Generazioni_CdnServers] FOREIGN KEY([FK_CDNSERVER])
REFERENCES [dbo].[CdnServers] ([ID])
GO
ALTER TABLE [dbo].[Generazioni] CHECK CONSTRAINT [FK_Generazioni_CdnServers]
GO
ALTER TABLE [dbo].[Generazioni]  WITH CHECK ADD  CONSTRAINT [FK_Generazioni_FtpServers] FOREIGN KEY([FK_FTPSERVER])
REFERENCES [dbo].[FtpServers] ([Id])
GO
ALTER TABLE [dbo].[Generazioni] CHECK CONSTRAINT [FK_Generazioni_FtpServers]
GO
ALTER TABLE [dbo].[Risorse]  WITH CHECK ADD  CONSTRAINT [FK_Risorse_TipologieTesti] FOREIGN KEY([FK_TIPOLOGIA])
REFERENCES [dbo].[TipologieTesti] ([ID])
GO
ALTER TABLE [dbo].[Risorse] CHECK CONSTRAINT [FK_Risorse_TipologieTesti]
GO
ALTER TABLE [dbo].[TestiPerRisorsa]  WITH CHECK ADD  CONSTRAINT [FK_TestiPerRisorsa_Risorse] FOREIGN KEY([RISORSA])
REFERENCES [dbo].[Risorse] ([ID])
GO
ALTER TABLE [dbo].[TestiPerRisorsa] CHECK CONSTRAINT [FK_TestiPerRisorsa_Risorse]
GO
ALTER TABLE [dbo].[TIpologieTestiPerVendor]  WITH CHECK ADD  CONSTRAINT [FK_TIpologieTestiPerVendor_TipologieTesti] FOREIGN KEY([FK_RESOURCETYPE])
REFERENCES [dbo].[TipologieTesti] ([ID])
GO
ALTER TABLE [dbo].[TIpologieTestiPerVendor] CHECK CONSTRAINT [FK_TIpologieTestiPerVendor_TipologieTesti]
GO
