name: Build
on:
  push:
   branches:
   - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
     solution-name: ${{ steps.setup-solution.outputs.solution }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Setup Solution
      id: setup-solution
      env: 
        SOLUTION_NAME: "Trinity.sln"
      run: |      
        echo "::set-output name=solution::$SOLUTION_NAME"
        echo "::set-output name=suffix::$suffix"
    - name: Install dependencies
      env: 
        SOLUTION_NAME: ${{ steps.setup-solution.outputs.solution }}
      run: |
       echo $SOLUTION_NAME
       dotnet restore $SOLUTION_NAME
    - name: Build Solution
      env: 
        SOLUTION_NAME: ${{ steps.setup-solution.outputs.solution }}
      run: dotnet build $SOLUTION_NAME --configuration Release --no-restore
